#!/bin/bash
cat nginx.templ|sed -e "s/SERVERNAME/${1}/" > /etc/nginx/conf.d/${1}.conf
systemctl reload nginx 
certbot certonly --server https://acme-v01.api.letsencrypt.org/directory  -a webroot --agree-tos -m email@email  --webroot-path=/opt/www/lets/ -d $1
cat nginx2.templ|sed -e "s/SERVERNAME/${1}/" > /etc/nginx/conf.d/${1}.conf
systemctl reload nginx

